version: '2'

# On windows first run: export COMPOSE_CONVERT_WINDOWS_PATHS=1
# Create service fails when this variable is unset

services:
    mara-www-store:
        container_name: mara-www-store
        image: centos:7 
        volumes:
            - /var/www/html
            - /c/Users/marek/workspace/php-wd15:/var/www/html/wd15-test
        command: /bin/true

    official-mariadb:
        container_name: official-mariadb
        image: mariadb:latest
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root-database-password
            - MYSQL_DATABASE=wd15
            - MYSQL_USER=wd15-database-user
            - MYSQL_PASSWORD=wd15-database-password
        volumes:
            - ./startup-database.sql:/docker-entrypoint-initdb.d/startup-database.sql

    mara-php-fpm:
        container_name: mara-php-fpm
        image: mara88/docker-centos7-php-fpm:latest
        links:
            - 'official-mariadb'
        depends_on:
            - 'official-mariadb'
        volumes_from:
            - 'mara-www-store'

    mara-apache:
        container_name: mara-apache
        image: mara88/docker-centos7-apache
        ports:
            - '80:80'
        links:
            - 'mara-php-fpm'
        depends_on:
            - 'mara-php-fpm'
        volumes_from:
            - 'mara-www-store'
        volumes:
            - ./get-app-from-github.sh:/docker-entrypoint-init.d/get-app-from-github.sh
            - ./configure-app-in-workspace.sh:/docker-entrypoint-reinit.d/configure-app-in-workspace.sh

    official-phpmyadmin:
        container_name: official-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        links: 
            - 'official-mariadb:db'
        environment:
            - MYSQL_ROOT_PASSWORD=root-database-password

